### ISSUE TITLE
Support for Forwarded Headers

### ISSUE THREAD

**Issue by schewara** [orhun/rustypaste#54]
I just came across this awesome project and was able to bring it up in no time.

During testing, I discovered that there is currently no feature to support Forwarded request headers, e.g.

- `X-Forwarded-For`
- `X-Forwarded-Host`
- `X-Forwarded-Proto`

This would be really useful to have for setups where the service is running behind a reverse-proxy or gateway and the possibility to adjust the logging output based on their availablity, to have the real IP addresses of the clients available in the log.

Thank you for creating such a useful tool and keep up the great work. :heart:

**Comment by orhun** [comment]
Thank you for your kind words and creating this issue!

I'm not exactly sure how to implement this for now but I got your point. I personally use Nginx reverse-proxy and set the headers as shown [in the example](https://github.com/orhun/rustypaste#nginx). Of course, it would be nice to have this feature built-in but I need to do some digging first.

If anyone else is interested, this issue is up for grabs!

**Comment by tessus** [comment]
@orhun I am using Apache as a reverse proxy and using the `ProxyPass` directive automatically adds the `X-Forward-*` headers (unless `ProxyAddHeaders Off` is explicitly set, since `On` is the default).

```
ProxyPass        /paste http://localhost:8020
ProxyPassReverse /paste http://localhost:8020
```

However, when I connect to `https://reverse.proxy.com/paste`, I see the following in the rustypaste log (even though the `X-Forward-*` headers are sent to rustypaste - verified with tcpdump):

```
[2023-06-12T02:22:15Z INFO  actix_web::middleware::logger] 127.0.0.1 "GET / HTTP/1.1" 200 271 "-" "Mozilla/5.0 Gecko/20100101 Firefox/114.0" 0.000036
```
