### ISSUE TITLE
Support .netrc

### ISSUE THREAD

**Issue by sayanarijit** [orhun/rustypaste#6]
It might be useful to be able to store the auth token in `~/.netrc` and avoid having to pass it via CLI.

**Comment by sayanarijit** [comment]
Ah, sorry. My bad. I thought it's the CLI.

**Comment by orhun** [comment]
TIL `.netrc` :)

**Comment by Soundtoxin** [comment]
I was just trying to figure out if .netrc was supported also, so I could make an alias to pipe to that uploads a file with curl to a rustypaste instance. I didn't want the auth token in my shell config since I track it in a public dotfiles repo. Seems .netrc is for basic user/pass auth and rustypaste uses a specific header that is neither user nor password, so is this not possible currently? Could support be added if so?

Not sure what OP meant by "I thought it's the CLI". I know you can upload from a browser, but I would like to upload with curl as well. Maybe worth reopening the issue.

**Comment by sayanarijit** [comment]
I probably meant https://github.com/orhun/rustypaste-cli. Can’t remember now…

**Comment by tessus** [comment]
> Seems .netrc is for basic user/pass auth and rustypaste uses a specific header that is neither user nor password, so is this not possible currently?

Not with `.netrc`, but as documented in the README.md, one can use a file that contains the headers:

```sh
function rpaste() {
  curl -F "file=@$1" -H "Authorization: <auth_token>" "<server_address>"
}
```

**\*** consider reading authorization headers from a file. (e.g. `-H @rpaste_auth`)

Thus you can do:

```
curl -F "file=@filename" -H @$HOME/.config/rustypaste.txt "<server_address>"
```

This works perfectly.

> Not sure what OP meant by "I thought it's the CLI".

Most likely the [rpaste](https://github.com/orhun/rustypaste-cli) cli, which actually uses a config file.

**Comment by Soundtoxin** [comment]
Thank you both for your responses. I glanced at the README a bit and searched for some stuff like "netrc" and "auth" but I missed that particular example in my quick skim.
